# Generated by Django 5.1.7 on 2025-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('last_mod', models.IntegerField()),
                ('load', models.IntegerField()),
                ('productivity', models.IntegerField()),
            ],
        ),
    ]
